# Generated by Django 4.1.5 on 2023-02-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer_num',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.IntegerField(choices=[(1, 'open'), (2, 'confirmed'), (3, 'complete')], default=1),
        ),
    ]
