# Generated by Django 4.1.5 on 2023-02-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideApp', '0002_ride_sharer_num_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='owner_passenger',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
